/*
 * DEVICE AND RELATED TO DEVICE
    * DEVICE_REGISTERED
    * DEVICE_EVENTS
    * PERSON_REGISTERED
 */

CREATE TABLE DEVICE(
 ID SERIAL PRIMARY KEY    NOT NULL,
 API_KEY        INT       NOT NULL, /* API KEY */
 USER_KEY       CHAR(32)  NOT NULL,
 PRIVATE_KEY    CHAR(32)  NOT NULL
);

CREATE TABLE DEVICE_REGISTERED(
 ID SERIAL PRIMARY KEY NOT NULL,
 ID_PERSON INT         NOT NULL
);

CREATE TYPE EVENTS_TYPE AS ENUM ('laps', 'lapsStart', 'lapsStop');

CREATE TABLE DEVICE_EVENTS(
  ID BIGSERIAL PRIMARY KEY   NOT NULL,
  TYPE        EVENTS_TYPE       NOT NULL,
  CREATED        TIMESTAMP        NOT NULL,
  CONTENT     VARCHAR(50) NOT NULL
);

CREATE TABLE PERSON_REGISTERED(
 ID SERIAL PRIMARY KEY   NOT NULL,
 TOKEN  VARCHAR(32)      NOT NULL,
 EMAIL       VARCHAR(50) NOT NULL
);

/*
 * PERSON AND RELATED TO PERSON
    * FRIENDS
    * DETAILS
    * AVATAR
    * BADGE
 */

CREATE TABLE PERSON(
  ID SERIAL PRIMARY KEY       NOT NULL,
  EMAIL   VARCHAR(50)  UNIQUE NOT NULL,
  CREATED         TIMESTAMP   NOT NULL,
  UPDATED         TIMESTAMP
);

CREATE TYPE PERSON_TYPE AS ENUM ('hamster', 'owner', 'apps', 'page', 'guild');

CREATE TABLE PERSON_DETAILS(
  ID SERIAL PRIMARY KEY NOT NULL,
  ID_PERSON INT         NOT NULL,
  TYPE PERSON_TYPE      NOT NULL,
  NAME VARCHAR(40),
  AVATAR INT            NULL
);

CREATE TABLE PERSON_FRIENDS(
  ID SERIAL PRIMARY KEY NOT NULL,
);


CREATE TABLE AVATAR (
  ID SERIAL PRIMARY KEY NOT NULL,
  ID_IMAGE BIGSERIAL UNIQUE NOT NULL,
);

CREATE TABLE AVATAR_DETAILS(
  ID BIGSERIAL PRIMARY KEY NOT NULL,
  ID_AVATAR SERIAL UNIQUE NOT NULL,
  CONTENT TEXT
)

/*
 * OTHERS
 */

CREATE IMAGE_TYPE AS ENUM ('jpg', 'png', 'gif');

CREATE TABLE IMAGE(
  ID BIGSERIAL PRIMARY KEY NOT NULL,
  RESOURCE VARCHAR(100),
  SIZE VARCHAR(9),
  TYPE IMAGE_TYPE
);


CREATE TABLE POST (
  ID BIGSERIAL PRIMARY KEY NOT NULL,
);


